name: Docker

on:
  push:
    paths:
      - "Dockerfile"
      paths-ignore:
      - "Dockerfile"
      - "README.md"
      - ".gihub/workflow/*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Login to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: brutewoorse
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish to Docker Hub
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: brutewoorse/mega-sdk-python:latest